
from __future__ import annotations

from pathlib import Path

APP_VERSION = "1.3.0"
PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "datasets"
DOCS_DIR = PROJECT_ROOT / "docs"
DEFAULT_SEED = 42
DEFAULT_N_ITER = 1_000
WORKING_DAYS_PER_YEAR = 300
DEFAULT_HOURS_PER_WORKDAY = 8.0
OFF_YEAR_FIXED_COST_SHARE = 0.20
CI_LOWER_Q = 0.025
CI_UPPER_Q = 0.975
CI_INTERVAL_LABEL = "95% CI"
ELIMINATION_DEFAULT_HORIZON = 15
WHO_EPHP_TARGET_YEAR = 2030
